#!/bin/bash

# by Alem Salmoor

u_menu=u_menu
t_menu=t_menu
f_menu=f_menu

menu_offset=8
day_of_week=$(($(date +%u) - 1))
start_idx=$(($day_of_week * $menu_offset + 1))

today=$(date +"%A, %d %B %Y")

wget -q -O $u_menu http://kafemud.bilkent.edu.tr/kumanya_menusu.pdf

if [ $? -eq 0 ]; then
	pdftotext $u_menu $t_menu
	cut -d '/' -f 2 -s $t_menu | grep -v Lunch | grep -v '^$' | sed 's/^[ \t]*//' > $f_menu

	for i in {0,1,2,3}; do
		lunch[$i]=$(sed "$(($start_idx + $i))q;d" $f_menu)
		dinner[$i]=$(sed "$(($start_idx + $i + 4))q;d" $f_menu)
	done;

	echo "	$today

	Lunch:
		1. ${lunch[0]}
		2. ${lunch[1]}
		3. ${lunch[2]}
		4. ${lunch[3]}

	Dinner:
		1. ${dinner[0]}
		2. ${dinner[1]}
		3. ${dinner[2]}
		4. ${dinner[3]}"
else
	echo "Can't fetch menu, check internet connection!"
	echo "Terminating"
fi

#Clean up
rm -f $u_menu $t_menu $f_menu
